### ISSUE TITLE
Pull RocksDB via Conan

### ISSUE THREAD

**Issue by johannes-wolf** [ndsev/mapget#46]
~~The most recent RocksDB version on conan.io is [6.29.5](https://conan.io/center/recipes/rocksdb?version=6.29.5) (current on github is [8.6.7](https://github.com/facebook/rocksdb/releases/)). Let's wait for conan.io to catch up (or open a PR) and pull RocksDB via conan.~~

Pull RocksDB from conan.io.
See https://conan.io/center/recipes/rocksdb?version=8.8.1

**Comment by MisterGC** [comment]
There is now rocksdb 8.8.1 available on conan, therefore this one should be unblocked, shouldn't it?

**Comment by johannes-wolf** [comment]
Nice! Was looking ~2 days ago and there was not… Yes, this in not blocked by the missing receipt anymore.

**Comment by johannes-wolf** [comment]
I've pushed this to #41
