### ISSUE TITLE
Feature Model API covers advanced feature relations.

### ISSUE THREAD

**Issue by MisterGC** [ndsev/mapget#53]
The current implementation of our Feature Model API permits basic linking of map features by utilizing their IDs as attributes. This method is effective for simple navigational tasks, allowing users to transition between related features with ease. However, this approach is somewhat limited, as it only facilitates basic ID-based connections without considering the complex relationships that can exist between map features.

We need to enhance the Feature Model API to encompass a broader range of feature relations. The revised API should enable defining relations that go beyond mere ID linking, allowing for associations based on specific segments or characteristics of other features. For instance, it should support scenarios like "Feature A is related to Feature B (e.g. visible from), but this relation is valid only within a particular section of Feature B's geometry."

Some additional thoughts/ideas:

How would we model "Feature A, a public park, is related to Feature B, a residential area, because they share a characteristic of being in a 'low-pollution zone.'” - should it be covered by relations too? The key difference is to the previous example is that this about grouping.

**Comment by josephbirkner** [comment]
To solve this, the feature will be amended with an additional relation collection. A relation consists of:
* A relation type (`visibleFrom`, `connectedTo`, `has`, `belongsTo`, `ADJACENT_LEFT`...).
* Optional source validity geometry.
* Optional destination validity geometry.
* An optional destination feature id.
